
# =========================
# HTML uzantılarını gizle
# =========================

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/anasayfa"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/sanalofis"
  to = "/sanalofis.html"
  status = 200

[[redirects]]
  from = "/hakkımızda"
  to = "/hakkimizda.html"
  status = 200

[[redirects]]
  from = "/iletisim"
  to = "/iletisim.html"
  status = 200


# =========================
# POLİTİKA SAYFALARI
# =========================

[[redirects]]
  from = "/hizmet-politikasi"
  to = "/hizmet-politikasi.html"
  status = 200

[[redirects]]
  from = "/cerez-politikasi"
  to = "/cerez-politikasi.html"
  status = 200

[[redirects]]
  from = "/gizlilik-politikasi"
  to = "/gizlilik-politikasi.html"
  status = 200